use_frameworks!

platform :ios, '8.0'

target 'BinartOCStickerKeyboard_Example' do
  pod 'BinartOCStickerKeyboard', :path => '../'

  target 'BinartOCStickerKeyboard_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
